import { Workflow } from "@/types";

export const CAKE_SHOP_WORKFLOW: Workflow = {
  id: "wf_cake_shop_default",
  businessId: "biz_cake_haven",
  name: "Cake Order & Enquiry Intake",
  description: "Handles missed calls for custom cakes, pastry orders, and party deliveries. Automatically flags urgent orders (< 24 hrs).",
  industry: "cake_shop",
  trigger: "missed_call",
  isActive: true,
  greeting: "Hello! Thanks for calling Sweet Delights Bakery. I'm your AI assistant. I'm sorry we missed your call. How can I help you with your cake or dessert order today?",
  greetingHi: "नमस्ते! स्वीट डिलाइट्स बेकरी में कॉल करने के लिए धन्यवाद। हम आपकी कॉल नहीं उठा पाए। मैं आपकी केक या डेज़र्ट आर्डर में क्या मदद कर सकता हूँ?",
  greetingKn: "ನಮಸ್ಕಾರ! ಸ್ವೀಟ್ ಡಿಲೈಟ್ಸ್ ಬೇಕರಿಗೆ ಕರೆ ಮಾಡಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ನಾನು ನಿಮ್ಮ AI ಸಹಾಯಕ. ನಿಮ್ಮ ಕೇಕ್ ಅಥವಾ ಡೆಸರ್ಟ್ ಆರ್ಡರ್‌ಗಾಗಿ ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
  personality: "warm_friendly",
  language: "en",
  fields: [
    {
      id: "f_cust_name",
      name: "customer_name",
      label: "Customer Name",
      type: "text",
      required: true,
      question: "May I have your name, please?",
      questionHi: "कृपया अपना नाम बताएं?",
      questionKn: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ತಿಳಿಸಿ?",
      order: 1,
    },
    {
      id: "f_cake_type",
      name: "cake_type",
      label: "Cake Type / Occasion",
      type: "select",
      required: true,
      options: ["Birthday Cake", "Wedding Cake", "Anniversary Cake", "Custom Theme Cake", "Pastries / Cupcakes", "Other"],
      question: "What kind of cake or occasion are you celebrating?",
      questionHi: "आप किस अवसर या किस प्रकार का केक आर्डर करना चाहते हैं?",
      questionKn: "ನೀವು ಯಾವ ಸಂದರ್ಭಕ್ಕಾಗಿ ಅಥವಾ ಯಾವ ರೀತಿಯ ಕೇಕ್ ಆರ್ಡರ್ ಮಾಡಲು ಬಯಸುತ್ತೀರಿ?",
      order: 2,
    },
    {
      id: "f_flavor",
      name: "flavor",
      label: "Cake Flavor",
      type: "text",
      required: true,
      question: "What flavor would you like? (e.g., Chocolate Truffle, Red Velvet, Vanilla Bean, Butterscotch)",
      questionHi: "आप कौन सा फ्लेवर पसंद करेंगे? (जैसे चॉकलेट, रेड वेलवेट, वैनिला)?",
      questionKn: "ನೀವು ಯಾವ ಫ್ಲೇವರ್ ಬಯಸುತ್ತೀರಿ? (ಉದಾ. ಚಾಕೊಲೇಟ್ ಟ್ರಫಲ್, ರೆಡ್ ವೆಲ್ವೆಟ್, ವೆನಿಲ್ಲಾ)?",
      order: 3,
    },
    {
      id: "f_weight",
      name: "weight",
      label: "Weight / Servings",
      type: "text",
      required: true,
      question: "What size or weight do you need (e.g. 1 kg, 2 kg, or for how many people)?",
      questionHi: "आपको कितने किलो या कितने लोगों के लिए केक चाहिए?",
      questionKn: "ನಿಮಗೆ ಎಷ್ಟು ಕೆಜಿ ಅಥವಾ ಎಷ್ಟು ಜನರಿಗೆ ಕೇಕ್ ಬೇಕು?",
      order: 4,
    },
    {
      id: "f_req_date",
      name: "required_date",
      label: "Required Date & Time",
      type: "date",
      required: true,
      question: "For what date and time do you need the cake ready?",
      questionHi: "आपको यह केक किस तारीख और समय पर चाहिए?",
      questionKn: "ನಿಮಗೆ ಈ ಕೇಕ್ ಯಾವ ದಿನಾಂಕ ಮತ್ತು ಸಮಯಕ್ಕೆ ಬೇಕು?",
      order: 5,
    },
    {
      id: "f_custom_msg",
      name: "custom_message",
      label: "Custom Message on Cake",
      type: "text",
      required: false,
      question: "Would you like any special name or message written on the cake?",
      questionHi: "क्या आप केक पर कोई विशेष नाम या संदेश लिखवाना चाहते हैं?",
      questionKn: "ಕೇಕ್ ಮೇಲೆ ಯಾವುದೇ ವಿಶೇಷ ಹೆಸರು ಅಥವಾ ಸಂದೇಶ ಬರೆಯಬೇಕೆ?",
      order: 6,
    },
    {
      id: "f_delivery_type",
      name: "delivery_type",
      label: "Delivery or Store Pickup",
      type: "select",
      required: true,
      options: ["Store Pickup", "Home Delivery"],
      question: "Would you prefer store pickup or home delivery?",
      questionHi: "क्या आप दुकान से पिकअप करेंगे या होम डिलीवरी चाहते हैं?",
      questionKn: "ನೀವು ಅಂಗಡಿಯಿಂದ ಪಿಕಪ್ ಮಾಡಲು ಬಯಸುವಿರಾ ಅಥವಾ ಮನೆ ಬಾಗಿಲಿಗೆ ಡೆಲಿವರಿ ಬೇಕೇ?",
      order: 7,
    },
    {
      id: "f_budget",
      name: "budget",
      label: "Approximate Budget",
      type: "text",
      required: false,
      question: "Do you have an approximate budget in mind?",
      questionHi: "क्या आपका कोई अनुमानित बजट है?",
      questionKn: "ನಿಮ್ಮ ಅಂದಾಜು ಬಜೆಟ್ ಎಷ್ಟು?",
      order: 8,
    },
    {
      id: "f_phone",
      name: "phone_number",
      label: "Contact Phone Number",
      type: "phone",
      required: true,
      question: "What is the best phone number to confirm your order details?",
      questionHi: "ऑर्डर कन्फर्म करने के लिए आपका सबसे अच्छा फोन नंबर क्या है?",
      questionKn: "ಆರ್ಡರ್ ದೃಢೀಕರಿಸಲು ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ತಿಳಿಸಿ?",
      order: 9,
    },
  ],
  conditions: [
    {
      id: "cond_cake_urgency",
      fieldId: "f_req_date",
      operator: "within_hours",
      value: 24,
      thenUrgency: "HIGH",
      thenAction: "mark_urgent",
      elseUrgency: "NORMAL",
      description: "If required date is within 24 hours, mark as HIGH urgency for expedited baking.",
    },
  ],
  actions: [
    {
      id: "act_create_cust",
      type: "create_customer",
      name: "Create/Update Customer Record",
      description: "Saves caller details to the CRM",
      config: {},
      enabled: true,
    },
    {
      id: "act_create_task",
      type: "create_task",
      name: "Create Bakery Prep Task",
      description: "Generates a bakery task to confirm recipe and send quote",
      config: { title: "Confirm Cake Order & Send Invoice" },
      enabled: true,
    },
    {
      id: "act_notify",
      type: "send_notification",
      name: "Notify Head Baker",
      description: "Sends in-app alert to bakery staff",
      config: {},
      enabled: true,
    },
  ],
  closingMessage: "Thank you so much! I have captured all your cake details. Our head baker will review this right away and message you a confirmation quote shortly. Have a wonderful day!",
  closingMessageHi: "बहुत-बहुत धन्यवाद! मैंने आपके ऑर्डर का सारा विवरण नोट कर लिया है। हमारे बेकर जल्द ही आपसे संपर्क करके पुष्टि करेंगे। आपका दिन शुभ हो!",
  closingMessageKn: "ತುಂಬಾ ಧನ್ಯವಾದಗಳು! ನಿಮ್ಮ ಆರ್ಡರ್‌ನ ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ದಾಖಲಿಸಲಾಗಿದೆ. ನಮ್ಮ ಹೆಡ್ ಬೇಕರ್ ಶೀಘ್ರದಲ್ಲೇ ಪರಿಶೀಲಿಸಿ ನಿಮಗೆ ದೃಢೀಕರಣ ಸಂದೇಶ ಕಳುಹಿಸುತ್ತಾರೆ. ಶುಭ ದಿನ!",
  ownerNotification: {
    notifyOnUrgent: true,
    notifyOnAll: true,
    channels: ["in_app", "email"],
    emailRecipient: "orders@sweetdelights.demo",
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const CLINIC_WORKFLOW: Workflow = {
  id: "wf_clinic_default",
  businessId: "biz_metro_health",
  name: "Doctor Appointment & Patient Triage",
  description: "Automates appointment booking, rescheduling, and doctor availability checks with Google Calendar integration. Includes strict medical disclaimer.",
  industry: "clinic",
  trigger: "missed_call",
  isActive: true,
  greeting: "Hello, thank you for calling Metro Health Care Clinic. I am the clinic's virtual assistant. Please note that I cannot provide medical advice or handle medical emergencies. How may I assist with your appointment today?",
  greetingHi: "नमस्ते, मेट्रो हेल्थ क्लिनिक में कॉल करने के लिए धन्यवाद। मैं क्लिनिक का वर्चुअल असिस्टेंट हूँ। कृपया ध्यान दें कि मैं डॉक्टरी सलाह नहीं दे सकता। अपॉइंटमेंट के लिए मैं आपकी क्या मदद करूँ?",
  greetingKn: "ನಮಸ್ಕಾರ, ಮೆಟ್ರೋ ಹೆಲ್ತ್ ಕೇರ್ ಕ್ಲಿನಿಕ್‌ಗೆ ಕರೆ ಮಾಡಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ನಾನು ಕ್ಲಿನಿಕ್‌ನ ವರ್ಚುವಲ್ ಸಹಾಯಕ. ದಯವಿಟ್ಟು ಗಮನಿಸಿ, ನಾನು ವೈದ್ಯಕೀಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿಗಳನ್ನು ನಿಭಾಯಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ. ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಾಗಿ ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
  personality: "professional",
  language: "en",
  fields: [
    {
      id: "f_patient_name",
      name: "patient_name",
      label: "Patient Full Name",
      type: "text",
      required: true,
      question: "May I have the patient's full name?",
      questionHi: "कृपया मरीज का पूरा नाम बताएं?",
      questionKn: "ದಯವಿಟ್ಟು ರೋಗಿಯ ಪೂರ್ಣ ಹೆಸರನ್ನು ತಿಳಿಸಿ?",
      order: 1,
    },
    {
      id: "f_intent",
      name: "appointment_intent",
      label: "Appointment Intent",
      type: "select",
      required: true,
      options: ["Book New Appointment", "Reschedule Appointment", "Cancel Appointment", "General Enquiry"],
      question: "Are you looking to book a new appointment, reschedule, or check doctor availability?",
      questionHi: "क्या आप नया अपॉइंटमेंट बुक करना चाहते हैं, तारीख बदलना चाहते हैं, या पूछताछ करना चाहते हैं?",
      questionKn: "ನೀವು ಹೊಸ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಲು, ಮರುಹೊಂದಿಸಲು ಅಥವಾ ವೈದ್ಯರ ಲಭ್ಯತೆಯನ್ನು ಪರಿಶೀಲಿಸಲು ಬಯಸುವಿರಾ?",
      order: 2,
    },
    {
      id: "f_doctor_spec",
      name: "doctor_speciality",
      label: "Doctor or Specialty",
      type: "select",
      required: true,
      options: ["General Physician (Dr. Sharma)", "Dentist (Dr. Kapoor)", "Cardiologist (Dr. Mehta)", "Pediatrician (Dr. Iyer)", "Dermatologist (Dr. Patel)"],
      question: "Which doctor or specialty would you like to consult?",
      questionHi: "आप किस डॉक्टर या विशेषज्ञ से मिलना चाहते हैं?",
      questionKn: "ನೀವು ಯಾವ ವೈದ್ಯರನ್ನು ಅಥವಾ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಲು ಬಯಸುತ್ತೀರಿ?",
      order: 3,
    },
    {
      id: "f_pref_date",
      name: "preferred_date",
      label: "Preferred Date",
      type: "date",
      required: true,
      question: "What date would you prefer for the appointment?",
      questionHi: "आप किस तारीख को आना चाहेंगे?",
      questionKn: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಾಗಿ ನೀವು ಯಾವ ದಿನಾಂಕವನ್ನು ಬಯಸುತ್ತೀರಿ?",
      order: 4,
    },
    {
      id: "f_pref_time",
      name: "preferred_time",
      label: "Preferred Time Slot",
      type: "time",
      required: true,
      question: "What time works best for you (e.g. morning 10 AM, afternoon 3 PM, evening 6 PM)?",
      questionHi: "आपके लिए कौन सा समय सही रहेगा (जैसे सुबह 10 बजे, दोपहर 3 बजे या शाम 6 बजे)?",
      questionKn: "ನಿಮಗೆ ಯಾವ ಸಮಯ ಅನುಕೂಲಕರವಾಗಿರುತ್ತದೆ (ಉದಾ. ಬೆಳಿಗ್ಗೆ 10:00, ಮಧ್ಯಾಹ್ನ 3:00 ಅಥವಾ ಸಂಜೆ 6:00)?",
      order: 5,
    },
    {
      id: "f_patient_phone",
      name: "phone_number",
      label: "Contact Phone Number",
      type: "phone",
      required: true,
      question: "Please confirm your phone number for appointment SMS confirmation.",
      questionHi: "कृपया कन्फर्मेशन मैसेज के लिए अपना मोबाइल नंबर बताएं।",
      questionKn: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ SMS ದೃಢೀಕರಣಕ್ಕಾಗಿ ದಯವಿಟ್ಟು ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ತಿಳಿಸಿ.",
      order: 6,
    },
  ],
  conditions: [
    {
      id: "cond_emergency_check",
      fieldId: "f_intent",
      operator: "equals",
      value: "Cancel Appointment",
      thenUrgency: "NORMAL",
      thenAction: "cancel_calendar_event",
      elseUrgency: "NORMAL",
      description: "If patient requests cancellation, trigger calendar cancellation tool.",
    },
  ],
  actions: [
    {
      id: "act_gcal_book",
      type: "create_calendar_event",
      name: "Sync to Google Calendar",
      description: "Books the verified slot on the clinic's Google Calendar",
      config: { durationMinutes: 30 },
      enabled: true,
    },
    {
      id: "act_create_patient",
      type: "create_customer",
      name: "Create Patient Profile",
      description: "Registers patient in clinic CRM",
      config: {},
      enabled: true,
    },
    {
      id: "act_notif_doc",
      type: "send_notification",
      name: "Alert Clinic Desk",
      description: "Sends appointment notification to receptionist",
      config: {},
      enabled: true,
    },
  ],
  closingMessage: "Your appointment details have been scheduled and synced with our calendar. You will receive an SMS reminder prior to your visit. If you experience severe symptoms, please seek emergency care. Thank you!",
  closingMessageHi: "आपका अपॉइंटमेंट दर्ज कर लिया गया है। आपको एसएमएस पर विवरण मिल जाएगा। मेट्रो हेल्थ क्लिनिक चुनने के लिए धन्यवाद!",
  closingMessageKn: "ನಿಮ್ಮ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ನಿಗದಿಯಾಗಿದೆ ಮತ್ತು ಗೂಗಲ್ ಕ್ಯಾಲೆಂಡರ್‌ನಲ್ಲಿ ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ. ನಿಮಗೆ SMS ಜ್ಞಾಪನೆ ಬರುತ್ತದೆ. ಮೆಟ್ರೋ ಹೆಲ್ತ್ ಕ್ಲಿನಿಕ್ ಆಯ್ಕೆ ಮಾಡಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು!",
  ownerNotification: {
    notifyOnUrgent: true,
    notifyOnAll: true,
    channels: ["in_app", "email"],
    emailRecipient: "reception@metrohealth.demo",
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const DELIVERY_WORKFLOW: Workflow = {
  id: "wf_delivery_default",
  businessId: "biz_swift_route",
  name: "Delivery Request & Tracking Helpdesk",
  description: "Assists customers with shipment pickup requests, tracking inquiries, and routing support. Seamlessly interfaces with tracking APIs.",
  industry: "delivery",
  trigger: "missed_call",
  isActive: true,
  greeting: "Hi! Thanks for calling SwiftRoute Logistics. I am your automated dispatch assistant. How can I help with your delivery or pickup today?",
  greetingHi: "नमस्ते! स्विफ्ट रूट लॉजिस्टिक्स में कॉल करने के लिए धन्यवाद। मैं आपका डिलीवरी असिस्टेंट हूँ। आपकी डिलीवरी या पिकअप में क्या मदद करूँ?",
  greetingKn: "ನಮಸ್ಕಾರ! ಸ್ವಿಫ್ಟ್‌ರೂಟ್ ಲಾಜಿಸ್ಟಿಕ್ಸ್‌ಗೆ ಕರೆ ಮಾಡಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ನಾನು ನಿಮ್ಮ ಆಟೋಮೇಟೆಡ್ ಸಹಾಯಕ. ನಿಮ್ಮ ಡೆಲಿವರಿ ಅಥವಾ ಪಿಕಪ್‌ನಲ್ಲಿ ನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
  personality: "concise",
  language: "en",
  fields: [
    {
      id: "f_sender_name",
      name: "customer_name",
      label: "Customer / Sender Name",
      type: "text",
      required: true,
      question: "May I have your name?",
      questionHi: "आपका नाम क्या है?",
      questionKn: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ತಿಳಿಸಿ?",
      order: 1,
    },
    {
      id: "f_req_type",
      name: "request_type",
      label: "Request Type",
      type: "select",
      required: true,
      options: ["New delivery", "Status update", "Existing delivery help"],
      question: "Are you calling for a new delivery booking, tracking status update, or help with an existing package?",
      questionHi: "क्या आप नई डिलीवरी बुक करना चाहते हैं, स्टेटस जानना चाहते हैं, या किसी पैकेज के लिए सहायता चाहिए?",
      questionKn: "ನೀವು ಹೊಸ ಡೆಲಿವರಿ ಬುಕಿಂಗ್ ಮಾಡಲು, ಟ್ರ್ಯಾಕಿಂಗ್ ಸ್ಥಿತಿ ತಿಳಿಯಲು ಅಥವಾ ಸಹಾಯ ಪಡೆಯಲು ಕರೆ ಮಾಡಿದ್ದೀರಾ?",
      order: 2,
    },
    {
      id: "f_tracking_num",
      name: "tracking_number",
      label: "Order / Tracking Number",
      type: "text",
      required: false,
      question: "If you have a tracking or order number (e.g. DEL-9821), could you please provide it?",
      questionHi: "यदि आपके पास ट्रैकिंग या आर्डर नंबर है (जैसे DEL-9821), तो कृपया बताएं?",
      questionKn: "ನಿಮ್ಮ ಬಳಿ ಟ್ರ್ಯಾಕಿಂಗ್ ಅಥವಾ ಆರ್ಡರ್ ಸಂಖ್ಯೆ ಇದೆಯೇ (ಉದಾ. DEL-9821)?",
      order: 3,
    },
    {
      id: "f_pickup_loc",
      name: "pickup_location",
      label: "Pickup Location / Address",
      type: "address",
      required: false,
      question: "What is the pickup address or city?",
      questionHi: "पिकअप का पता या शहर क्या है?",
      questionKn: "ಪಿಕಪ್ ಮಾಡುವ ವಿಳಾಸ ಅಥವಾ ನಗರ ಯಾವುದು?",
      order: 4,
    },
    {
      id: "f_delivery_loc",
      name: "delivery_location",
      label: "Delivery Location / Address",
      type: "address",
      required: false,
      question: "What is the delivery destination address?",
      questionHi: "डिलीवरी का गंतव्य पता क्या है?",
      questionKn: "ಡೆಲಿವರಿ ತಲುಪಿಸಬೇಕಾದ ವಿಳಾಸ ಯಾವುದು?",
      order: 5,
    },
    {
      id: "f_package_type",
      name: "package_type",
      label: "Package Type & Weight",
      type: "select",
      required: false,
      options: ["Documents / Envelope", "Small Parcel (< 5kg)", "Medium Box (5-20kg)", "Heavy Freight / Pallet"],
      question: "What type of package is this (envelope, parcel, or freight)?",
      questionHi: "पैकेज किस प्रकार का है (दस्तावेज़, पार्सल या भारी सामान)?",
      questionKn: "ಪ್ಯಾಕೇಜ್ ಯಾವ ಪ್ರಕಾರದ್ದು (ದಾಖಲೆಗಳು, ಪಾರ್ಸೆಲ್ ಅಥವಾ ಭಾರಿ ಸರಕು)?",
      order: 6,
    },
    {
      id: "f_pref_pickup_time",
      name: "preferred_time",
      label: "Preferred Pickup Time",
      type: "time",
      required: false,
      question: "What is your preferred pickup time window?",
      questionHi: "पिकअप के लिए कौन सा समय सही रहेगा?",
      questionKn: "ಪಿಕಪ್ ಮಾಡಲು ನಿಮ್ಮ ಆದ್ಯತೆಯ ಸಮಯ ಯಾವುದು?",
      order: 7,
    },
    {
      id: "f_phone_num",
      name: "phone_number",
      label: "Contact Phone Number",
      type: "phone",
      required: true,
      question: "What phone number can our dispatch driver reach you at?",
      questionHi: "ड्राइवर आपसे किस नंबर पर संपर्क कर सकता है?",
      questionKn: "ಚಾಲಕ ಸಂಪರ್ಕಿಸಲು ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ಯಾವುದು?",
      order: 8,
    },
  ],
  conditions: [
    {
      id: "cond_delivery_help",
      fieldId: "f_req_type",
      operator: "equals",
      value: "Existing delivery help",
      thenUrgency: "HIGH",
      thenAction: "create_task",
      elseUrgency: "NORMAL",
      description: "If caller needs help with an existing delivery issue, mark as HIGH urgency for dispatch callback.",
    },
  ],
  actions: [
    {
      id: "act_delivery_task",
      type: "create_task",
      name: "Create Dispatch Task",
      description: "Queues task for route coordinator",
      config: { title: "Dispatch Logistics Follow-up" },
      enabled: true,
    },
    {
      id: "act_cust_logistics",
      type: "create_customer",
      name: "Save Logistics Client",
      description: "Stores client profile",
      config: {},
      enabled: true,
    },
    {
      id: "act_notif_dispatch",
      type: "send_notification",
      name: "Notify Dispatch Center",
      description: "Pushes alert to logistics team",
      config: {},
      enabled: true,
    },
  ],
  closingMessage: "Got it! Your logistics request has been logged. Our dispatch team is reviewing your route and will contact you directly with driver details. Thank you for choosing SwiftRoute!",
  closingMessageHi: "आपका अनुरोध दर्ज कर लिया गया है। हमारी डिस्पैच टीम जल्द ही आपसे संपर्क करेगी। स्विफ्ट रूट चुनने के लिए धन्यवाद!",
  closingMessageKn: "ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ದಾಖಲಿಸಲಾಗಿದೆ. ನಮ್ಮ ರವಾನೆ ತಂಡವು ಶೀಘ್ರದಲ್ಲೇ ಚಾಲಕರ ವಿವರಗಳೊಂದಿಗೆ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ. ಧನ್ಯವಾದಗಳು!",
  ownerNotification: {
    notifyOnUrgent: true,
    notifyOnAll: true,
    channels: ["in_app", "email"],
    emailRecipient: "dispatch@swiftroute.demo",
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const REAL_ESTATE_WORKFLOW: Workflow = {
  id: "wf_real_estate_default",
  businessId: "biz_prime_realty",
  name: "Property Enquiry & Site Visit Scheduler",
  description: "Handles missed calls for property buyers, tenants, and sellers. Qualifies budget, property type, location, and books site visits on Google Calendar.",
  industry: "real_estate",
  trigger: "missed_call",
  isActive: true,
  greeting: "Hello! Thank you for calling Prime Properties & Realty. I'm your virtual real-estate assistant. How can I help you with your property search or site visit today?",
  greetingHi: "नमस्ते! प्राइम प्रॉपर्टीज में कॉल करने के लिए धन्यवाद। मैं आपका रियल एस्टेट असिस्टेंट हूँ। प्रॉपर्टी सर्च या साइट विजिट में मैं आपकी क्या मदद करूँ?",
  greetingKn: "ನಮಸ್ಕಾರ! ಪ್ರೈಮ್ ಪ್ರಾಪರ್ಟೀಸ್‌ಗೆ ಕರೆ ಮಾಡಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ನಾನು ನಿಮ್ಮ ವರ್ಚುವಲ್ ರಿಯಲ್ ಎಸ್ಟೇಟ್ ಸಹಾಯಕ. ಆಸ್ತಿ ಹುಡುಕಾಟ ಅಥವಾ ಸೈಟ್ ಭೇಟಿಯಲ್ಲಿ ನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
  personality: "professional",
  language: "en",
  fields: [
    {
      id: "f_re_name",
      name: "customer_name",
      label: "Client Full Name",
      type: "text",
      required: true,
      question: "May I have your full name, please?",
      questionHi: "कृपया अपना पूरा नाम बताएं?",
      questionKn: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ತಿಳಿಸಿ?",
      order: 1,
    },
    {
      id: "f_re_intent",
      name: "property_intent",
      label: "Intent (Buy / Rent / Sell / Site Visit)",
      type: "select",
      required: true,
      options: ["Buy Property", "Rent / Lease", "Sell Property", "Schedule Site Visit"],
      question: "Are you looking to buy, rent, sell, or schedule a property site visit?",
      questionHi: "क्या आप प्रॉपर्टी खरीदना, किराए पर लेना, बेचना चाहते हैं या साइट विजिट करना चाहते हैं?",
      questionKn: "ನೀವು ಪ್ರಾಪರ್ಟಿ ಖರೀದಿಸಲು, ಬಾಡಿಗೆಗೆ ಪಡೆಯಲು, ಮಾರಾಟ ಮಾಡಲು ಅಥವಾ ಸೈಟ್ ಭೇಟಿ ನಿಗದಿಪಡಿಸಲು ಬಯಸುವಿರಾ?",
      order: 2,
    },
    {
      id: "f_re_type",
      name: "property_type",
      label: "Property Type",
      type: "select",
      required: true,
      options: ["2 BHK Apartment", "3 BHK Apartment", "Luxury Villa", "Commercial Office / Retail", "Plot / Land"],
      question: "What type of property are you interested in (e.g. 2 BHK, 3 BHK, Villa, or Commercial)?",
      questionHi: "आप किस प्रकार की प्रॉपर्टी ढूंढ रहे हैं (2 BHK, 3 BHK, विला या कमर्शियल)?",
      questionKn: "ನೀವು ಯಾವ ರೀತಿಯ ಪ್ರಾಪರ್ಟಿಯನ್ನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ (ಉದಾ. 2 BHK, 3 BHK ಅಥವಾ ವಿಲ್ಲಾ)?",
      order: 3,
    },
    {
      id: "f_re_location",
      name: "preferred_location",
      label: "Preferred Location / City",
      type: "text",
      required: true,
      question: "Which locality, neighborhood, or city are you searching in?",
      questionHi: "आप किस इलाके या शहर में प्रॉपर्टी देख रहे हैं?",
      questionKn: "ನೀವು ಯಾವ ಸ್ಥಳ ಅಥವಾ ಪ್ರದೇಶವನ್ನು ಬಯಸುತ್ತೀರಿ?",
      order: 4,
    },
    {
      id: "f_re_budget",
      name: "budget",
      label: "Target Budget Range",
      type: "text",
      required: false,
      question: "What is your target budget range?",
      questionHi: "आपका अनुमानित बजट क्या है?",
      questionKn: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಬಜೆಟ್ ವ್ಯಾಪ್ತಿ ಎಷ್ಟು?",
      order: 5,
    },
    {
      id: "f_re_visit_date",
      name: "visit_date",
      label: "Preferred Site Visit Date",
      type: "date",
      required: false,
      question: "If you'd like a site visit, what date and time works best for you?",
      questionHi: "साइट विजिट के लिए कौन सी तारीख और समय सही रहेगा?",
      questionKn: "ಸೈಟ್ ಭೇಟಿಗಾಗಿ ನೀವು ಯಾವ ದಿನ ಮತ್ತು ಸಮಯವನ್ನು ಬಯಸುತ್ತೀರಿ?",
      order: 6,
    },
    {
      id: "f_re_phone",
      name: "phone_number",
      label: "Contact Phone Number",
      type: "phone",
      required: true,
      question: "What is the best phone number for our senior property agent to reach you?",
      questionHi: "प्रॉपर्टी एजेंट द्वारा संपर्क के लिए आपका फोन नंबर क्या है?",
      questionKn: "ವಿವರಗಳನ್ನು ಕಳುಹಿಸಲು ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ತಿಳಿಸಿ?",
      order: 7,
    },
  ],
  conditions: [
    {
      id: "cond_re_high_budget",
      fieldId: "f_re_intent",
      operator: "equals",
      value: "Schedule Site Visit",
      thenUrgency: "HIGH",
      thenAction: "create_calendar_event",
      elseUrgency: "NORMAL",
      description: "Immediate site visit requests flagged as HIGH priority for prompt agent confirmation.",
    },
  ],
  actions: [
    {
      id: "act_re_cust",
      type: "create_customer",
      name: "Create Buyer Profile in CRM",
      description: "Registers buyer preferences and budget in CRM",
      config: {},
      enabled: true,
    },
    {
      id: "act_re_visit",
      type: "create_calendar_event",
      name: "Schedule Property Site Visit (GCal)",
      description: "Reserves property visit on Google Calendar",
      config: { durationMinutes: 60 },
      enabled: true,
    },
    {
      id: "act_re_notif",
      type: "send_notification",
      name: "Alert Real Estate Agent",
      description: "Notifies real estate consultant of new qualified lead",
      config: {},
      enabled: true,
    },
  ],
  closingMessage: "Fantastic! I've recorded your property criteria. Our senior consultant will review available listings matching your budget and reach out shortly. Thank you for contacting Prime Properties!",
  closingMessageHi: "बहुत बढ़िया! मैंने आपकी प्रॉपर्टी का विवरण नोट कर लिया है। हमारे कंसलटेंट जल्द ही आपसे संपर्क करेंगे। धन्यवाद!",
  closingMessageKn: "ಧನ್ಯವಾದಗಳು! ನಿಮ್ಮ ಸೈಟ್ ಭೇಟಿಯನ್ನು ಗೂಗಲ್ ಕ್ಯಾಲೆಂಡರ್‌ನಲ್ಲಿ ನಿಗದಿಪಡಿಸಲಾಗಿದೆ. ನಮ್ಮ ಪ್ರಾಪರ್ಟಿ ಸಲಹೆಗಾರರು ಶೀಘ್ರದಲ್ಲೇ ಸಂಪರ್ಕಿಸುತ್ತಾರೆ. ಶುಭ ದಿನ!",
  ownerNotification: {
    notifyOnUrgent: true,
    notifyOnAll: true,
    channels: ["in_app", "email"],
    emailRecipient: "leads@primerealty.demo",
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const REPAIR_SERVICE_WORKFLOW: Workflow = {
  id: "wf_repair_default",
  businessId: "biz_fixit_services",
  name: "Emergency Repair & Home Service Triage",
  description: "Handles missed calls for emergency plumbing, electrical, and appliance repairs. Flags urgent water leaks or power outages for priority technician dispatch.",
  industry: "repair_service",
  trigger: "missed_call",
  isActive: true,
  greeting: "Hello! Thanks for calling FixIt Home & Repair Services. I'm your virtual service assistant. Are you facing an emergency repair or scheduling regular maintenance today?",
  greetingHi: "नमस्ते! फिक्स-इट रिपेयर सर्विसेज में कॉल करने के लिए धन्यवाद। क्या आपको कोई इमरजेंसी रिपेयर चाहिए या सामान्य सर्विस बुक करनी है?",
  greetingKn: "ನಮಸ್ಕಾರ! ಕ್ವಿಕ್‌ಫಿಕ್ಸ್ ಹೋಮ್ ಸರ್ವಿಸಸ್‌ಗೆ ಕರೆ ಮಾಡಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ಪ್ಲಂಬಿಂಗ್, ಎಲೆಕ್ಟ್ರಿಕಲ್ ಅಥವಾ ಗೃಹೋಪಯೋಗಿ ವಸ್ತುಗಳ ರಿಪೇರಿಯಲ್ಲಿ ನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
  personality: "concise",
  language: "en",
  fields: [
    {
      id: "f_rep_name",
      name: "customer_name",
      label: "Customer Name",
      type: "text",
      required: true,
      question: "May I have your name, please?",
      questionHi: "आपका नाम क्या है?",
      questionKn: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ತಿಳಿಸಿ?",
      order: 1,
    },
    {
      id: "f_rep_service_type",
      name: "service_type",
      label: "Repair Service Type",
      type: "select",
      required: true,
      options: ["Plumbing (Leak / Blockage)", "Electrical (Power Outage / Wiring)", "AC & HVAC Repair", "Appliance Repair", "Carpentry / General"],
      question: "What service do you need (e.g., plumbing, electrical, AC repair, or appliance)?",
      questionHi: "आपको किस प्रकार की सर्विस चाहिए (जैसे प्लंबिंग, बिजली, एसी या उपकरण रिपेयर)?",
      questionKn: "ನಿಮಗೆ ಯಾವ ರೀತಿಯ ಸೇವೆ ಅಗತ್ಯವಿದೆ (ಪ್ಲಂಬಿಂಗ್, ಎಲೆಕ್ಟ್ರಿಕಲ್ ಅಥವಾ AC ಸರ್ವಿಸ್)?",
      order: 2,
    },
    {
      id: "f_rep_issue",
      name: "issue_description",
      label: "Issue Description",
      type: "text",
      required: true,
      question: "Could you briefly describe the issue or symptom?",
      questionHi: "कृपया समस्या का संक्षेप में विवरण दें?",
      questionKn: "ಸಮಸ್ಯೆಯನ್ನು ಸಂಕ್ಷಿಪ್ತವಾಗಿ ವಿವರಿಸಿ?",
      order: 3,
    },
    {
      id: "f_rep_address",
      name: "address",
      label: "Service Address",
      type: "address",
      required: true,
      question: "What is your home or site address for the technician visit?",
      questionHi: "टेक्नीशियन के आने के लिए आपका पता क्या है?",
      questionKn: "ಸೇವಾ ವಿಳಾಸ ಅಥವಾ ಪ್ರದೇಶ ಯಾವುದು?",
      order: 4,
    },
    {
      id: "f_rep_urgency",
      name: "urgency_flag",
      label: "Urgency (Emergency / Normal)",
      type: "select",
      required: true,
      options: ["Emergency (Within 2 hours)", "Today", "Tomorrow / Scheduled"],
      question: "Is this an immediate emergency (e.g. active water leak) or a scheduled visit?",
      questionHi: "क्या यह तत्काल इमरजेंसी है या सामान्य विजिट?",
      questionKn: "ಇದು ತಕ್ಷಣದ ತುರ್ತು ರಿಪೇರಿಯೇ ಅಥವಾ ಸಾಮಾನ್ಯ ಭೇಟಿಯೇ?",
      order: 5,
    },
    {
      id: "f_rep_time",
      name: "preferred_time",
      label: "Preferred Visit Time",
      type: "time",
      required: false,
      question: "What time would you prefer our technician to visit?",
      questionHi: "टेक्नीशियन के आने का कौन सा समय सही रहेगा?",
      questionKn: "ತಂತ್ರಜ್ಞರು ಯಾವಾಗ ಭೇಟಿ ನೀಡಬೇಕೆಂದು ಬಯಸುತ್ತೀರಿ?",
      order: 6,
    },
    {
      id: "f_rep_phone",
      name: "phone_number",
      label: "Contact Phone Number",
      type: "phone",
      required: true,
      question: "What phone number should our dispatch technician call before arriving?",
      questionHi: "टेक्नीशियन आपसे किस नंबर पर संपर्क करे?",
      questionKn: "ತಂತ್ರಜ್ಞರು ಸಂಪರ್ಕಿಸಲು ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ಯಾವುದು?",
      order: 7,
    },
  ],
  conditions: [
    {
      id: "cond_rep_emergency",
      fieldId: "f_rep_urgency",
      operator: "contains",
      value: "Emergency",
      thenUrgency: "CRITICAL",
      thenAction: "send_notification",
      elseUrgency: "NORMAL",
      description: "Active emergencies flagged as CRITICAL for instant on-call technician dispatch.",
    },
  ],
  actions: [
    {
      id: "act_rep_task",
      type: "create_task",
      name: "Dispatch Technician Task",
      description: "Assigns repair job to on-duty technician",
      config: { title: "Emergency Repair Dispatch" },
      enabled: true,
    },
    {
      id: "act_rep_gcal",
      type: "create_calendar_event",
      name: "Book Technician Slot on GCal",
      description: "Schedules service window in technician Google Calendar",
      config: { durationMinutes: 45 },
      enabled: true,
    },
    {
      id: "act_rep_cust",
      type: "create_customer",
      name: "Save Customer Profile",
      description: "Registers service address and customer in CRM",
      config: {},
      enabled: true,
    },
  ],
  closingMessage: "Got it! Your repair ticket has been logged. Our dispatch coordinator is assigning the nearest certified technician. For emergencies, a technician will call you within 15 minutes. Thank you!",
  closingMessageHi: "आपका रिपेयर टिकट दर्ज कर लिया गया है। हमारे टेक्नीशियन जल्द ही आपसे संपर्क करेंगे। धन्यवाद!",
  closingMessageKn: "ನಿಮ್ಮ ಸೇವಾ ವಿನಂತಿಯನ್ನು ತುರ್ತಾಗಿ ದಾಖಲಿಸಲಾಗಿದೆ. ನಮ್ಮ ತಜ್ಞ ತಂತ್ರಜ್ಞರು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮ ವಿಳಾಸಕ್ಕೆ ತಲುಪುತ್ತಾರೆ. ಧನ್ಯವಾದಗಳು!",
  ownerNotification: {
    notifyOnUrgent: true,
    notifyOnAll: true,
    channels: ["in_app", "email", "sms"],
    emailRecipient: "dispatch@fixitservices.demo",
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const PREBUILT_TEMPLATES: Record<string, Workflow> = {
  cake_shop: CAKE_SHOP_WORKFLOW,
  clinic: CLINIC_WORKFLOW,
  delivery: DELIVERY_WORKFLOW,
  real_estate: REAL_ESTATE_WORKFLOW,
  repair_service: REPAIR_SERVICE_WORKFLOW,
};
