import { Business, Workflow, Conversation, Customer, CalendarEvent, Task, NotificationItem } from "@/types";
import { CAKE_SHOP_WORKFLOW, CLINIC_WORKFLOW, DELIVERY_WORKFLOW, REAL_ESTATE_WORKFLOW, REPAIR_SERVICE_WORKFLOW } from "../workflow/templates";

export const DEMO_BUSINESSES: Business[] = [
  {
    id: "biz_cake_haven",
    name: "Sweet Delights Artisan Bakery",
    type: "cake_shop",
    phone: "+1 (555) 789-2253",
    email: "orders@sweetdelights.demo",
    address: "452 Maple Avenue, Suite 10, Downtown",
    timezone: "America/New_York",
    language: "en",
    createdAt: "2026-08-15T09:00:00Z",
    updatedAt: "2026-08-28T14:30:00Z",
  },
  {
    id: "biz_metro_health",
    name: "Metro Health Care Clinic",
    type: "clinic",
    phone: "+91 98765 00100",
    email: "reception@metrohealth.demo",
    address: "Block C-4, Outer Ring Road, Bengaluru",
    timezone: "Asia/Kolkata",
    language: "en",
    createdAt: "2026-08-10T08:00:00Z",
    updatedAt: "2026-08-30T11:00:00Z",
  },
  {
    id: "biz_swift_route",
    name: "SwiftRoute Express Logistics",
    type: "delivery",
    phone: "+1 (555) 349-8800",
    email: "dispatch@swiftroute.demo",
    address: "Hub 4, North Cargo Terminal, Chicago",
    timezone: "America/Chicago",
    language: "en",
    createdAt: "2026-08-01T07:00:00Z",
    updatedAt: "2026-08-31T16:00:00Z",
  },
  {
    id: "biz_prime_realty",
    name: "Prime Properties & Realty",
    type: "real_estate",
    phone: "+1 (555) 670-9911",
    email: "leads@primerealty.demo",
    address: "Tower 2, Financial District, New York",
    timezone: "America/New_York",
    language: "en",
    createdAt: "2026-08-05T09:00:00Z",
    updatedAt: "2026-08-31T12:00:00Z",
  },
  {
    id: "biz_fixit_services",
    name: "FixIt Home & Emergency Repair",
    type: "repair_service",
    phone: "+1 (555) 432-8877",
    email: "dispatch@fixitservices.demo",
    address: "88 Industrial Way, Austin",
    timezone: "America/Chicago",
    language: "en",
    createdAt: "2026-08-08T08:00:00Z",
    updatedAt: "2026-08-31T14:00:00Z",
  },
];

export const DEMO_WORKFLOWS: Workflow[] = [
  CAKE_SHOP_WORKFLOW,
  CLINIC_WORKFLOW,
  DELIVERY_WORKFLOW,
  REAL_ESTATE_WORKFLOW,
  REPAIR_SERVICE_WORKFLOW,
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: "cust_rahul",
    businessId: "biz_cake_haven",
    name: "Rahul Verma",
    phone: "+91 98765 43210",
    email: "rahul.verma@example.com",
    address: "Flat 402, Sunshine Heights",
    notes: "Prefers eggless dark chocolate cakes. Always requests expedited pickup.",
    latestUrgency: "HIGH",
    lastInteractionAt: "2026-09-01T10:15:00Z",
    totalConversations: 3,
    extractedAttributes: {
      preferred_flavor: "Dark Chocolate Truffle",
      typical_budget: "₹1500 - ₹2500",
      family_events: "Son's Birthday in Sep",
    },
    createdAt: "2026-08-20T11:00:00Z",
    updatedAt: "2026-09-01T10:15:00Z",
  },
  {
    id: "cust_ananya",
    businessId: "biz_metro_health",
    name: "Ananya Kapoor",
    phone: "+91 98111 22334",
    email: "ananya.k@example.com",
    notes: "Consults Dr. Kapoor for dental checkups. Mild dental anxiety.",
    latestUrgency: "NORMAL",
    lastInteractionAt: "2026-09-01T09:30:00Z",
    totalConversations: 2,
    extractedAttributes: {
      assigned_doctor: "Dr. Kapoor (Dentist)",
      last_procedure: "Root Canal Follow-up",
    },
    createdAt: "2026-08-18T14:20:00Z",
    updatedAt: "2026-09-01T09:30:00Z",
  },
  {
    id: "cust_marcus",
    businessId: "biz_swift_route",
    name: "Marcus Vance",
    phone: "+1 (555) 678-9012",
    email: "marcus.v@logistix.com",
    address: "742 Evergreen Terrace",
    notes: "Requires gate code #4492 for parcel drops.",
    latestUrgency: "HIGH",
    lastInteractionAt: "2026-09-01T08:45:00Z",
    totalConversations: 4,
    extractedAttributes: {
      tracking_id: "DEL-9821",
      carrier_route: "Route 12 - Southside",
    },
    createdAt: "2026-08-12T09:00:00Z",
    updatedAt: "2026-09-01T08:45:00Z",
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: "conv_cake_urgent",
    businessId: "biz_cake_haven",
    workflowId: "wf_cake_shop_default",
    customerId: "cust_rahul",
    callerNumber: "+91 98765 43210",
    callerName: "Rahul Verma",
    status: "new",
    urgency: "HIGH",
    intent: "Urgent Birthday Cake Enquiry",
    language: "en",
    extractedFields: {
      customer_name: "Rahul Verma",
      cake_type: "Birthday Cake",
      flavor: "Chocolate Truffle",
      weight: "2 kg",
      required_date: "Tomorrow at 4 PM",
      custom_message: "Happy 5th Birthday Aarav!",
      delivery_type: "Store Pickup",
      budget: "₹1800",
      phone_number: "+91 98765 43210",
    },
    summary: "Customer Rahul Verma needs a 2kg Chocolate Truffle Birthday Cake ready tomorrow by 4 PM for store pickup. Custom text: 'Happy 5th Birthday Aarav!'. Flagged HIGH urgency due to < 24-hour turnaround.",
    messages: [
      {
        id: "msg_1",
        conversationId: "conv_cake_urgent",
        role: "assistant",
        content: "Hello! Thanks for calling Sweet Delights Bakery. I'm your AI assistant. I'm sorry we missed your call. How can I help you with your cake or dessert order today?",
        timestamp: "2026-09-01T10:10:00Z",
      },
      {
        id: "msg_2",
        conversationId: "conv_cake_urgent",
        role: "user",
        content: "Hi! I need a 2kg chocolate birthday cake for tomorrow afternoon, my name is Rahul.",
        timestamp: "2026-09-01T10:11:15Z",
      },
      {
        id: "msg_3",
        conversationId: "conv_cake_urgent",
        role: "assistant",
        content: "Got it Rahul! What flavor would you like (such as Chocolate Truffle, Red Velvet, or Black Forest)? And would you like any special message written on top?",
        timestamp: "2026-09-01T10:11:18Z",
      },
      {
        id: "msg_4",
        conversationId: "conv_cake_urgent",
        role: "user",
        content: "Make it Chocolate Truffle. Write 'Happy 5th Birthday Aarav!'. I'll pick it up at 4 PM tomorrow. Budget is around 1800.",
        timestamp: "2026-09-01T10:12:40Z",
      },
      {
        id: "msg_5",
        conversationId: "conv_cake_urgent",
        role: "assistant",
        content: "Thank you so much Rahul! I have captured all your cake details for the 2kg Chocolate Truffle cake. Because it's needed tomorrow, our head baker has been alerted immediately and will send your confirmation invoice shortly.",
        timestamp: "2026-09-01T10:12:44Z",
      },
    ],
    toolCalls: [],
    createdAt: "2026-09-01T10:10:00Z",
    updatedAt: "2026-09-01T10:13:00Z",
    completedAt: "2026-09-01T10:13:00Z",
  },
  {
    id: "conv_clinic_booking",
    businessId: "biz_metro_health",
    workflowId: "wf_clinic_default",
    customerId: "cust_ananya",
    callerNumber: "+91 98111 22334",
    callerName: "Ananya Kapoor",
    status: "contacted",
    urgency: "NORMAL",
    intent: "Book Dental Consultation",
    language: "en",
    extractedFields: {
      patient_name: "Ananya Kapoor",
      appointment_intent: "Book New Appointment",
      doctor_speciality: "Dentist (Dr. Kapoor)",
      preferred_date: "Tomorrow",
      preferred_time: "3:00 PM",
      phone_number: "+91 98111 22334",
    },
    summary: "Patient Ananya Kapoor scheduled a dental appointment with Dr. Kapoor for tomorrow at 3:00 PM. Verified calendar slot and synchronized Google Calendar event successfully.",
    messages: [
      {
        id: "msg_c1",
        conversationId: "conv_clinic_booking",
        role: "assistant",
        content: "Hello, thank you for calling Metro Health Care Clinic. I am the clinic virtual assistant. How may I assist with your appointment today?",
        timestamp: "2026-09-01T09:25:00Z",
      },
      {
        id: "msg_c2",
        conversationId: "conv_clinic_booking",
        role: "user",
        content: "Hello, I want to book a dental checkup with Dr. Kapoor tomorrow at 3 PM. My name is Ananya Kapoor.",
        timestamp: "2026-09-01T09:26:10Z",
      },
      {
        id: "msg_c3",
        conversationId: "conv_clinic_booking",
        role: "assistant",
        content: "I checked our Google Calendar and confirmed your appointment with Dr. Kapoor for tomorrow at 3:00 PM. Calendar invitation has been created.",
        timestamp: "2026-09-01T09:26:15Z",
      },
    ],
    toolCalls: [
      {
        id: "tc_gcal_1",
        toolName: "calendar.checkAvailability",
        input: { date: "Tomorrow", time: "3:00 PM", durationMinutes: 30 },
        output: { available: true, slot: "Tomorrow at 3:00 PM", status: "available" },
        status: "success",
        executionTimeMs: 142,
        timestamp: "2026-09-01T09:26:12Z",
      },
      {
        id: "tc_gcal_2",
        toolName: "calendar.createEvent",
        input: {
          title: "Dental Consultation - Ananya Kapoor",
          attendeeName: "Ananya Kapoor",
          date: "Tomorrow",
          time: "3:00 PM",
        },
        output: {
          eventId: "gcal_evt_9918",
          title: "Dental Consultation - Ananya Kapoor",
          status: "confirmed",
        },
        status: "success",
        executionTimeMs: 230,
        timestamp: "2026-09-01T09:26:14Z",
      },
    ],
    createdAt: "2026-09-01T09:25:00Z",
    updatedAt: "2026-09-01T09:27:00Z",
    completedAt: "2026-09-01T09:27:00Z",
  },
  {
    id: "conv_logistics_track",
    businessId: "biz_swift_route",
    workflowId: "wf_delivery_default",
    customerId: "cust_marcus",
    callerNumber: "+1 (555) 678-9012",
    callerName: "Marcus Vance",
    status: "completed",
    urgency: "HIGH",
    intent: "Urgent Package Status Inquiry",
    language: "en",
    extractedFields: {
      customer_name: "Marcus Vance",
      request_type: "Existing delivery help",
      tracking_number: "DEL-9821",
      phone_number: "+1 (555) 678-9012",
    },
    summary: "Marcus called inquiring about express package DEL-9821. Tool execution confirmed package is Out for Delivery with driver Vikram S. Callback scheduled.",
    messages: [
      {
        id: "msg_d1",
        conversationId: "conv_logistics_track",
        role: "assistant",
        content: "Hi! Thanks for calling SwiftRoute Logistics. How can I help with your delivery or pickup today?",
        timestamp: "2026-09-01T08:40:00Z",
      },
      {
        id: "msg_d2",
        conversationId: "conv_logistics_track",
        role: "user",
        content: "Where is my urgent package DEL-9821? I need it before 5 PM.",
        timestamp: "2026-09-01T08:41:00Z",
      },
      {
        id: "msg_d3",
        conversationId: "conv_logistics_track",
        role: "assistant",
        content: "I tracked your shipment DEL-9821. Status: Out for Delivery. Current location: Sector 14 (3.2 km away). Estimated arrival is today by 4:30 PM with driver Vikram S.",
        timestamp: "2026-09-01T08:41:04Z",
      },
    ],
    toolCalls: [
      {
        id: "tc_del_1",
        toolName: "delivery.trackPackage",
        input: { trackingNumber: "DEL-9821" },
        output: {
          trackingNumber: "DEL-9821",
          status: "Out for Delivery",
          currentLocation: "Sector 14 (3.2 km away)",
          estimatedDelivery: "Today by 4:30 PM",
        },
        status: "success",
        executionTimeMs: 110,
        timestamp: "2026-09-01T08:41:02Z",
      },
    ],
    createdAt: "2026-09-01T08:40:00Z",
    updatedAt: "2026-09-01T08:42:00Z",
    completedAt: "2026-09-01T08:42:00Z",
  },
  {
    id: "conv_hindi_demo",
    businessId: "biz_metro_health",
    workflowId: "wf_clinic_default",
    callerNumber: "+91 99887 76655",
    callerName: "Ramesh Sharma",
    status: "new",
    urgency: "NORMAL",
    intent: "Doctor Consultation (Hindi)",
    language: "hi",
    extractedFields: {
      patient_name: "Ramesh Sharma",
      appointment_intent: "Book New Appointment",
      doctor_speciality: "General Physician (Dr. Sharma)",
      preferred_date: "Tomorrow",
      preferred_time: "Evening (6:00 PM)",
      phone_number: "+91 99887 76655",
    },
    summary: "मरीज रमेश शर्मा ने कल शाम 6 बजे डॉ. शर्मा (जनरल फिजिशियन) के साथ अपॉइंटमेंट बुक किया। गूगल कैलेंडर में स्लॉट सफलतापूर्वक दर्ज कर लिया गया।",
    messages: [
      {
        id: "msg_h1",
        conversationId: "conv_hindi_demo",
        role: "assistant",
        content: "नमस्ते, मेट्रो हेल्थ क्लिनिक में कॉल करने के लिए धन्यवाद। मैं क्लिनिक का वर्चुअल असिस्टेंट हूँ। अपॉइंटमेंट के लिए मैं आपकी क्या मदद करूँ?",
        timestamp: "2026-09-01T07:15:00Z",
      },
      {
        id: "msg_h2",
        conversationId: "conv_hindi_demo",
        role: "user",
        content: "मुझे कल शाम 6 बजे डॉक्टर शर्मा से मिलना है। मेरा नाम रमेश है।",
        timestamp: "2026-09-01T07:16:00Z",
      },
      {
        id: "msg_h3",
        role: "assistant",
        conversationId: "conv_hindi_demo",
        content: "बहुत बढ़िया रमेश जी! मैंने कैलेंडर चेक करके कल शाम 6:00 बजे डॉ. शर्मा के साथ आपका अपॉइंटमेंट दर्ज कर लिया है।",
        timestamp: "2026-09-01T07:16:05Z",
      },
    ],
    toolCalls: [
      {
        id: "tc_gcal_hi",
        toolName: "calendar.createEvent",
        input: {
          title: "Clinic Consultation: Ramesh Sharma",
          date: "Tomorrow",
          time: "6:00 PM",
        },
        output: {
          eventId: "gcal_evt_hi_1",
          status: "confirmed",
          message: "Slot reserved on Google Calendar",
        },
        status: "success",
        executionTimeMs: 180,
        timestamp: "2026-09-01T07:16:03Z",
      },
    ],
    createdAt: "2026-09-01T07:15:00Z",
    updatedAt: "2026-09-01T07:17:00Z",
    completedAt: "2026-09-01T07:17:00Z",
  },
];

export const DEMO_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: "evt_1",
    businessId: "biz_metro_health",
    customerId: "cust_ananya",
    conversationId: "conv_clinic_booking",
    title: "Dental Consultation: Ananya Kapoor",
    description: "Tooth examination with Dr. Kapoor. Auto-scheduled via CallPilot AI.",
    startTime: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() + 24.5 * 3600 * 1000).toISOString(),
    attendeeName: "Ananya Kapoor",
    attendeePhone: "+91 98111 22334",
    attendeeEmail: "ananya.k@example.com",
    status: "confirmed",
    googleEventId: "gcal_evt_9918",
    createdAt: "2026-09-01T09:26:14Z",
    updatedAt: "2026-09-01T09:26:14Z",
  },
  {
    id: "evt_2",
    businessId: "biz_metro_health",
    conversationId: "conv_hindi_demo",
    title: "General Checkup: Ramesh Sharma",
    description: "Consultation with Dr. Sharma. Hindi virtual intake.",
    startTime: new Date(Date.now() + 27 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() + 27.5 * 3600 * 1000).toISOString(),
    attendeeName: "Ramesh Sharma",
    attendeePhone: "+91 99887 76655",
    status: "confirmed",
    googleEventId: "gcal_evt_hi_1",
    createdAt: "2026-09-01T07:16:03Z",
    updatedAt: "2026-09-01T07:16:03Z",
  },
  {
    id: "evt_3",
    businessId: "biz_cake_haven",
    customerId: "cust_rahul",
    conversationId: "conv_cake_urgent",
    title: "Cake Pickup: Rahul Verma (2kg Chocolate Truffle)",
    description: "Expedited order pickup. Ready by 4 PM.",
    startTime: new Date(Date.now() + 25 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() + 25.5 * 3600 * 1000).toISOString(),
    attendeeName: "Rahul Verma",
    attendeePhone: "+91 98765 43210",
    status: "confirmed",
    createdAt: "2026-09-01T10:13:00Z",
    updatedAt: "2026-09-01T10:13:00Z",
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: "task_1",
    businessId: "biz_cake_haven",
    conversationId: "conv_cake_urgent",
    customerId: "cust_rahul",
    title: "Send Quote & Confirm Aarav's 5th Bday Cake",
    description: "2kg Chocolate Truffle for Rahul Verma. Due tomorrow 4 PM.",
    dueDate: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    priority: "HIGH",
    completed: false,
    createdAt: "2026-09-01T10:13:00Z",
  },
  {
    id: "task_2",
    businessId: "biz_swift_route",
    conversationId: "conv_logistics_track",
    customerId: "cust_marcus",
    title: "Coordinate Urgent Parcel DEL-9821 Delivery",
    description: "Ensure driver drops parcel before 4:30 PM gate code #4492.",
    dueDate: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    priority: "HIGH",
    completed: false,
    createdAt: "2026-09-01T08:42:00Z",
  },
  {
    id: "task_3",
    businessId: "biz_metro_health",
    conversationId: "conv_clinic_booking",
    title: "Send Dental Pre-Consultation SMS Reminders",
    description: "Send medical questionnaire to Ananya Kapoor.",
    dueDate: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
    priority: "NORMAL",
    completed: true,
    createdAt: "2026-09-01T09:27:00Z",
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif_1",
    businessId: "biz_cake_haven",
    title: "Urgent Customer Enquiry Received",
    message: "Rahul Verma requested a 2kg custom cake within 24 hours. High urgency flagged.",
    type: "urgent_call",
    isRead: false,
    conversationId: "conv_cake_urgent",
    createdAt: "2026-09-01T10:13:00Z",
  },
  {
    id: "notif_2",
    businessId: "biz_metro_health",
    title: "New Google Calendar Appointment Synced",
    message: "Ananya Kapoor booked Dental Consultation for tomorrow at 3:00 PM.",
    type: "appointment_booked",
    isRead: false,
    conversationId: "conv_clinic_booking",
    createdAt: "2026-09-01T09:27:00Z",
  },
  {
    id: "notif_3",
    businessId: "biz_swift_route",
    title: "Dispatch Alert: Expedited Shipment Query",
    message: "Marcus Vance inquired on package DEL-9821 out for delivery.",
    type: "order_enquiry",
    isRead: true,
    conversationId: "conv_logistics_track",
    createdAt: "2026-09-01T08:42:00Z",
  },
];
